title: Crossroads Digital Design Kit
email: design@crossroads.net
description: >- # this means to ignore newlines until "baseurl:"
  Crossroads Digital Design Kit, or DDK, is the official pattern library for Crossroads.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://design.crossroads.net/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# Include in processing.
# Redirects needed to be declared for Netlify
include:
  - _redirects

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  # - vendor
  - README.md

# Assets declared for jekyll-assets gem
assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: false # true on JEKYLL_ENV=production
  js_compressor: uglifier
  sources:
    - _assets/stylesheets
    - _assets/javascripts

typekit_url: https://use.typekit.net/ccb3vpa.css

imgix_params:
  jumbotron: "auto=format,compress&w=100&fit=crop"
  placeholder: "auto=format,compress&w=10"
  placeholder_clip: "auto=format,compress&w=100&fit=clip"
  placeholder_square: "auto=format,compress&w=10&h=10&fit=crop"
  placeholder_sixteen_nine: "auto=format,compress&w=16&h=9&fit=crop"

image_sizes:
  cards_3x: "(min-width: 1200px) 360px, (min-width: 992px) 294px, (min-width: 768px) 720px, 100vw"
  full_width: "100vw"
  half_width: "50vw"
